sources:
  - name: smsc1
    mode: sftp
    host: "129.13.0.125"
    port: 22
    username: "parser"
    password: "131095Ss!"
    path: "/sftp/cdr/SMS"

  - name: smsc2
    mode: sftp
    host: "129.13.0.123"
    port: 22
    username: "parser"
    password: "131095Ss!"
    path: "/sftp/cdr/SMS"
